# Generated by Django 5.2.14 on 2026-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='additional_resources',
            field=models.TextField(blank=True, help_text='Links to additional learning resources'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='common_mistakes',
            field=models.TextField(blank=True, help_text='Common mistakes and how to avoid them'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='key_concepts',
            field=models.TextField(blank=True, help_text='List of key concepts, one per line or comma-separated'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='What students will learn in this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_exercises',
            field=models.TextField(blank=True, help_text='Practice exercises for students'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_questions_json',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of quiz questions for this lesson'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Minimum score percentage to pass'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='example_code',
            field=models.TextField(blank=True, help_text='Code examples with syntax highlighting'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theory_content',
            field=models.TextField(blank=True, help_text='Main lesson content with HTML formatting'),
        ),
    ]
